### PR TITLE
add github actions workflow for CI

### PR DESCRIPTION
**Pull request by tdyas**
Use Rust GitHub actions to implement CI.

### CODE REVIEW

**Comment by tdyas** [comment]
Hmm, the new CI job fails on macOS:

```
---- tests::roundtrip_heartbeat_success stdout ----
Got connection: TcpStream { addr: 127.0.0.1:50797, peer: 127.0.0.1:50798, fd: 12 }
thread 'tests::roundtrip_heartbeat_success' panicked at 'assertion failed: `(left == right)`
  left: `ExitCode(67)`,
 right: `ExitCode(-2)`', nails/src/lib.rs:214:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::roundtrip_heartbeat_success

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by stuhood** [comment]
Possibly racey... sorry about that.

**Comment by tdyas** [comment]
> Possibly racey... sorry about that.

Probably something to fix before this lands? Or maybe make this CI job be non-blocking for now?

**Comment by stuhood** [comment]
I'm fine with non-blocking for now.

I assume that there be a post-merge step to actually enable it?

**Comment by tdyas** [comment]
> I assume that there be a post-merge step to actually enable it?

I forget offhand what the default is, but the repo settings under "Checks" lets you mark an Action as required or not.

**Comment by stuhood** [comment]
Thanks a lot!

**Pull request merged**
